# Please consult conda-forge/core before doing this
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "11.3"                 # [osx and x86_64]
  - "11.3"                 # [osx and aarch64]
MACOSX_SDK_VERSION:        # [osx]
  - "11.3"                 # [osx and x86_64]
  - "11.3"                 # [osx and aarch64]
